# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggy_pi', '0002_auto_20160612_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpipin',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veggy_pi.Sensor'),
        ),
    ]
