# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lhs', models.TextField(blank=True, default=None)),
                ('rhs', models.TextField(blank=True, default=None)),
                ('operator', models.PositiveIntegerField(choices=[(4, '=='), (5, '!='), (6, '>'), (7, '<'), (8, '>='), (9, '<=')], default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.PositiveIntegerField(choices=[(1, 'AND'), (2, 'OR')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfigurationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=30)),
                ('parent_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veggy_pi.ConfigurationOption')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_name', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RPiPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(editable=False)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('current_reading', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_sensor', to='veggy_pi.Reading')),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggy_pi.ConfigurationOption')),
            ],
        ),
        migrations.CreateModel(
            name='VeggyConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('parent_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veggy_pi.VeggyConfiguration')),
                ('user_config', models.ManyToManyField(through='veggy_pi.UserInput', to='veggy_pi.ConfigurationOption')),
            ],
        ),
        migrations.AddField(
            model_name='userinput',
            name='veggy_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggy_pi.VeggyConfiguration'),
        ),
        migrations.AddField(
            model_name='rpipin',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggy_pi.Sensor'),
        ),
        migrations.AddField(
            model_name='reading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veggy_pi.Sensor'),
        ),
        migrations.AddField(
            model_name='condition',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='veggy_pi.ConditionGroup'),
        ),
        migrations.CreateModel(
            name='Thermometer',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('veggy_pi.sensor',),
        ),
        migrations.AlterUniqueTogether(
            name='userinput',
            unique_together=set([('veggy_config', 'variable')]),
        ),
    ]
