# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-12 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggy_pi', '0003_auto_20160612_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpipin',
            old_name='number',
            new_name='pin_number',
        ),
        migrations.AlterField(
            model_name='rpipin',
            name='label',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
