# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veggy_pi', '0004_auto_20160612_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.SmallIntegerField(editable=False)),
                ('label', models.CharField(editable=False, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='rpipin',
            name='sensor',
        ),
        migrations.CreateModel(
            name='DHT22Sensor',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('veggy_pi.sensor',),
        ),
        migrations.DeleteModel(
            name='RPiPin',
        ),
        migrations.AddField(
            model_name='sensor',
            name='pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veggy_pi.Pin'),
        ),
    ]
