# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggy_pi', '0005_auto_20160617_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 17, 14, 54, 49, 154783)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='data',
            field=models.TextField(default=datetime.datetime(2016, 6, 17, 14, 54, 59, 171137)),
            preserve_default=False,
        ),
    ]
